// Excel「敷き鉄板 貸出管理表」(2026/04/20更新版) から取り込んだ初期データ
const SEED_RECORDS = [
 {
  "id": "x001",
  "no": "R01",
  "count": 30,
  "lendDate": "2025-10-09",
  "company": "森崎",
  "site": "中川改修",
  "person": "高田",
  "note": "",
  "status": "returned",
  "returnInfo": "2/24撤去"
 },
 {
  "id": "x002",
  "no": "R02",
  "count": 2,
  "lendDate": "2025-10-10",
  "company": "玉家建設",
  "site": "森邸",
  "person": "専務",
  "note": "ゴムマット３枚も貸出",
  "status": "returned",
  "returnInfo": "2/14撤去"
 },
 {
  "id": "x003",
  "no": "R03",
  "count": 2,
  "lendDate": "2025-10-17",
  "company": "アクティオ富山",
  "site": "三菱ケミカル",
  "person": "北川",
  "note": "",
  "status": "returned",
  "returnInfo": "2026/1/20 撤去"
 },
 {
  "id": "x004",
  "no": "R04",
  "count": 0,
  "lendDate": "2025-10-23",
  "company": "玉家建設",
  "site": "新藤邸",
  "person": "専務",
  "note": "",
  "status": "returned",
  "returnInfo": "１１月８日３枚撤去"
 },
 {
  "id": "x005",
  "no": "R05",
  "count": 0,
  "lendDate": "2025-10-14",
  "company": "アクティオ富山",
  "site": "高速床板取替え",
  "person": "北川",
  "note": "※５×１０ ２枚 吉田商会（富山営）",
  "status": "returned",
  "returnInfo": "撤去済み"
 },
 {
  "id": "x006",
  "no": "R06",
  "count": 3,
  "lendDate": "2025-10-30",
  "company": "丸和ホーム",
  "site": "佐藤邸",
  "person": "専務",
  "note": "",
  "status": "returned",
  "returnInfo": "3/4撤去すみ"
 },
 {
  "id": "x007",
  "no": "R07",
  "count": 0,
  "lendDate": "2025-11-04",
  "company": "アクティオ西",
  "site": "稲積電気防食工事",
  "person": "北川",
  "note": "※４×８ ３枚（吉田商会（富山営）",
  "status": "returned",
  "returnInfo": "１７日撤去済み"
 },
 {
  "id": "x008",
  "no": "R08",
  "count": 6,
  "lendDate": "2025-11-03",
  "company": "パパマルハウス",
  "site": "西田邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "2/24撤去すみ"
 },
 {
  "id": "x009",
  "no": "01",
  "count": 3,
  "lendDate": "2025-11-05",
  "company": "玉家建設",
  "site": "棚本邸",
  "person": "専務",
  "note": "※ゴムマット８枚も貸出",
  "status": "returned",
  "returnInfo": "8月27日撤去すみ"
 },
 {
  "id": "x010",
  "no": "R09",
  "count": 0,
  "lendDate": "2025-11-03",
  "company": "パパマルハウス",
  "site": "大塚邸",
  "person": "杉村",
  "note": "※４×８ １枚",
  "status": "returned",
  "returnInfo": "１月１６日撤去済み"
 },
 {
  "id": "x011",
  "no": "R10",
  "count": 6,
  "lendDate": "2025-11-08",
  "company": "ベストホーム",
  "site": "前田邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "3月16日撤去"
 },
 {
  "id": "x012",
  "no": "R11",
  "count": 3,
  "lendDate": "2025-11-08",
  "company": "クオレホーム",
  "site": "城川邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "3月20日撤去"
 },
 {
  "id": "x013",
  "no": "R12",
  "count": 0,
  "lendDate": "2025-11-17",
  "company": "アクティオ富山",
  "site": "神工電気",
  "person": "北川",
  "note": "※３×６ ７枚（吉田商会（立山）",
  "status": "returned",
  "returnInfo": "１１月２１日 ７枚返却"
 },
 {
  "id": "x014",
  "no": "R13",
  "count": 3,
  "lendDate": "",
  "company": "クオレホーム",
  "site": "秦健太郎邸 南砺市",
  "person": "杉村",
  "note": "貸出日欄: 竹内",
  "status": "returned",
  "returnInfo": "3月17日撤去"
 },
 {
  "id": "x015",
  "no": "R14",
  "count": 3,
  "lendDate": "2025-11-24",
  "company": "パパマルハウス",
  "site": "光井様 滑川市",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "3/12日撤去"
 },
 {
  "id": "x016",
  "no": "R15",
  "count": 2,
  "lendDate": "2025-11-24",
  "company": "パパマルハウス",
  "site": "土田邸 金沢市",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "3月18日撤去"
 },
 {
  "id": "x017",
  "no": "02",
  "count": 5,
  "lendDate": "2025-11-28",
  "company": "クオレホーム",
  "site": "星場邸 氷見市",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "4月11日撤去"
 },
 {
  "id": "x018",
  "no": "R16",
  "count": 3,
  "lendDate": "2025-11-29",
  "company": "玉家建設",
  "site": "高橋邸 高岡市",
  "person": "専務",
  "note": "",
  "status": "returned",
  "returnInfo": "3月13日撤去"
 },
 {
  "id": "x019",
  "no": "03",
  "count": 3,
  "lendDate": "2025-12-12",
  "company": "クオレホーム",
  "site": "川端邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "4月14日撤去"
 },
 {
  "id": "x020",
  "no": "04",
  "count": 2,
  "lendDate": "2025-12-20",
  "company": "パパマルハウス",
  "site": "森邸 上二杉",
  "person": "杉村",
  "note": "※4×８ 3枚もレンタル",
  "status": "returned",
  "returnInfo": "4月14日撤去"
 },
 {
  "id": "x021",
  "no": "05",
  "count": 6,
  "lendDate": "2026-01-19",
  "company": "クロダハウス",
  "site": "黒川邸 神通町",
  "person": "専務",
  "note": "※ゴムマット6枚",
  "status": "returned",
  "returnInfo": "7月２４日撤去"
 },
 {
  "id": "x022",
  "no": "06",
  "count": 10,
  "lendDate": "2026-01-17",
  "company": "クオレホーム",
  "site": "朴美英邸 高岡市",
  "person": "杉村",
  "note": "※ロードマット4枚もレンタル",
  "status": "returned",
  "returnInfo": "5月7・８日撤去"
 },
 {
  "id": "x023",
  "no": "08",
  "count": 7,
  "lendDate": "2026-02-03",
  "company": "クオレホーム",
  "site": "中川邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "5月９日撤去"
 },
 {
  "id": "x024",
  "no": "09",
  "count": 6,
  "lendDate": "2026-02-07",
  "company": "ベストホーム",
  "site": "加賀見邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "6月２０日撤去"
 },
 {
  "id": "x025",
  "no": "10",
  "count": 7,
  "lendDate": "2026-02-11",
  "company": "ネイエ",
  "site": "野村久美子邸",
  "person": "福島",
  "note": "",
  "status": "returned",
  "returnInfo": "5月16日撤去"
 },
 {
  "id": "x026",
  "no": "11",
  "count": 3,
  "lendDate": "2026-02-17",
  "company": "パパマルハウス",
  "site": "谷口和幸",
  "person": "杉村",
  "note": "※3×６ 1枚 ニッショウ",
  "status": "returned",
  "returnInfo": "6月２7日撤去"
 },
 {
  "id": "x027",
  "no": "12",
  "count": 1,
  "lendDate": "2026-02-18",
  "company": "パパマルハウス",
  "site": "藤澤邸",
  "person": "杉村",
  "note": "※3×６ ４枚 ニッショウ",
  "status": "returned",
  "returnInfo": "6月２6日撤去"
 },
 {
  "id": "x028",
  "no": "13",
  "count": 20,
  "lendDate": "2026-02-16",
  "company": "東山住宅",
  "site": "山本様邸",
  "person": "北川",
  "note": "",
  "status": "returned",
  "returnInfo": "撤去"
 },
 {
  "id": "x029",
  "no": "14",
  "count": 1,
  "lendDate": "2026-02-19",
  "company": "丸和ホーム",
  "site": "水田邸",
  "person": "専務",
  "note": "",
  "status": "returned",
  "returnInfo": "7月9日撤去"
 },
 {
  "id": "x030",
  "no": "15",
  "count": 14,
  "lendDate": "2026-02-28",
  "company": "パパマルハウス",
  "site": "吉田邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "3月２８日撤去"
 },
 {
  "id": "x031",
  "no": "16",
  "count": 6,
  "lendDate": "2026-03-05",
  "company": "東山住宅",
  "site": "大島 隆司・成実邸",
  "person": "北川",
  "note": "",
  "status": "returned",
  "returnInfo": "撤去"
 },
 {
  "id": "x032",
  "no": "17",
  "count": 5,
  "lendDate": "2026-03-13",
  "company": "玉家建設",
  "site": "飯田邸",
  "person": "専務",
  "note": "4/21 2枚　6/1　4枚　追加   ※9/5日11枚撤去",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x033",
  "no": "18",
  "count": 6,
  "lendDate": "2026-03-16",
  "company": "ネイエ",
  "site": "堀川邸",
  "person": "福島",
  "note": "※6枚撤去済み　6/18",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x034",
  "no": "19",
  "count": 10,
  "lendDate": "2026-03-20",
  "company": "クオレホーム",
  "site": "湊孝広様邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "7月９日撤去"
 },
 {
  "id": "x035",
  "no": "20",
  "count": 2,
  "lendDate": "2026-03-24",
  "company": "パパマルハウス",
  "site": "小川様邸",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "7月１４日撤去"
 },
 {
  "id": "x036",
  "no": "21",
  "count": 8,
  "lendDate": "2026-03-28",
  "company": "ベストホーム",
  "site": "カプヤン",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "8月22日撤去"
 },
 {
  "id": "x037",
  "no": "22",
  "count": 8,
  "lendDate": "2026-04-02",
  "company": "ベストホーム",
  "site": "カプヤン",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "９月５日撤去"
 },
 {
  "id": "x038",
  "no": "23",
  "count": 6,
  "lendDate": "2026-04-01",
  "company": "クオレホーム",
  "site": "若林新樹様",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "6月２０日撤去"
 },
 {
  "id": "x039",
  "no": "24",
  "count": 6,
  "lendDate": "2026-04-09",
  "company": "ネイエ",
  "site": "堀川邸",
  "person": "福島",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x040",
  "no": "25",
  "count": 0,
  "lendDate": "2026-04-11",
  "company": "パパマルハウス",
  "site": "ファースト設計様37号",
  "person": "杉村",
  "note": "3×６　3枚　ニッショウ",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x041",
  "no": "26",
  "count": 16,
  "lendDate": "2026-04-16",
  "company": "野村土建",
  "site": "北部幹線（第3工区）",
  "person": "常務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x042",
  "no": "27",
  "count": 12,
  "lendDate": "2026-04-22",
  "company": "ベストホーム",
  "site": "ラゴス様邸",
  "person": "杉村",
  "note": "※6月13日　９枚追加",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x043",
  "no": "29",
  "count": 4,
  "lendDate": "2026-04-22",
  "company": "ダイチ",
  "site": "地すべり防止ボーリング工事",
  "person": "福島",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x044",
  "no": "30",
  "count": 103,
  "lendDate": "2026-04-29",
  "company": "土肥鉄工",
  "site": "富士化学工業㈱",
  "person": "高田",
  "note": "",
  "status": "returned",
  "returnInfo": "撤去済み"
 },
 {
  "id": "x045",
  "no": "31",
  "count": 8,
  "lendDate": "2026-04-23",
  "company": "パパマルハウス",
  "site": "加賀谷様",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "8月17日撤去済み"
 },
 {
  "id": "x046",
  "no": "32",
  "count": 6,
  "lendDate": "2026-04-25",
  "company": "クオレホーム",
  "site": "氷見瑞基様",
  "person": "杉村",
  "note": "",
  "status": "returned",
  "returnInfo": "8月１７日撤去済み"
 },
 {
  "id": "x047",
  "no": "33",
  "count": 2,
  "lendDate": "2026-05-09",
  "company": "パパマルハウス",
  "site": "山森新築工事",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x048",
  "no": "34",
  "count": 2,
  "lendDate": "2026-05-14",
  "company": "アクティオ富山",
  "site": "アピタ富山",
  "person": "北川",
  "note": "",
  "status": "returned",
  "returnInfo": "6月19日済み"
 },
 {
  "id": "x049",
  "no": "35",
  "count": 0,
  "lendDate": "2026-05-19",
  "company": "丸和ホーム",
  "site": "田屋邸",
  "person": "専務",
  "note": "3×６　１枚　ニッショウ",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x050",
  "no": "36",
  "count": 4,
  "lendDate": "2026-05-20",
  "company": "パパマルハウス",
  "site": "轡田邸",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x051",
  "no": "37",
  "count": 2,
  "lendDate": "2026-05-29",
  "company": "アクティオ富山",
  "site": "富山営",
  "person": "北川",
  "note": "",
  "status": "returned",
  "returnInfo": "6月１２日撤去"
 },
 {
  "id": "x052",
  "no": "38",
  "count": 4,
  "lendDate": "2026-06-01",
  "company": "玉家建設",
  "site": "飯田邸",
  "person": "専務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x053",
  "no": "39",
  "count": 4,
  "lendDate": "2026-06-05",
  "company": "一工業",
  "site": "はばたき歯科医院",
  "person": "高田",
  "note": "",
  "status": "returned",
  "returnInfo": "8月25日撤去"
 },
 {
  "id": "x054",
  "no": "40",
  "count": 2,
  "lendDate": "2026-06-05",
  "company": "丸和ホーム",
  "site": "藤井邸",
  "person": "専務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x055",
  "no": "42",
  "count": 2,
  "lendDate": "2026-06-18",
  "company": "東山住宅",
  "site": "法野邸",
  "person": "北川",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x056",
  "no": "43",
  "count": 7,
  "lendDate": "2026-06-30",
  "company": "玉家建設",
  "site": "松本邸",
  "person": "専務",
  "note": "3×６　1枚　ニッショウでレンタル",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x057",
  "no": "44",
  "count": 0,
  "lendDate": "2026-06-24",
  "company": "東山住宅",
  "site": "白岩邸",
  "person": "北川",
  "note": "3×６　3枚　吉田商会（富山営）レンタル",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x058",
  "no": "45",
  "count": 1,
  "lendDate": "2026-07-01",
  "company": "玉家建設",
  "site": "片山邸",
  "person": "専務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x059",
  "no": "46",
  "count": 12,
  "lendDate": "2026-07-14",
  "company": "アクティオ西",
  "site": "輪島港",
  "person": "北川",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x060",
  "no": "47",
  "count": 2,
  "lendDate": "2026-07-14",
  "company": "丸和ホーム",
  "site": "奥村邸",
  "person": "専務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x061",
  "no": "48",
  "count": 8,
  "lendDate": "2026-07-14",
  "company": "ベストホーム",
  "site": "寺崎邸",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x062",
  "no": "49",
  "count": 6,
  "lendDate": "2026-07-16",
  "company": "ネイエ",
  "site": "早苗邸",
  "person": "福島",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x063",
  "no": "",
  "count": 12,
  "lendDate": "2026-07-17",
  "company": "パパマルハウス",
  "site": "松尾邸",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x064",
  "no": "",
  "count": 5,
  "lendDate": "2026-07-24",
  "company": "トスモ",
  "site": "木戸邸",
  "person": "専務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x065",
  "no": "",
  "count": 2,
  "lendDate": "2026-07-24",
  "company": "すまいるホーム",
  "site": "中島邸",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x066",
  "no": "",
  "count": 0,
  "lendDate": "2026-07-28",
  "company": "玉家建設",
  "site": "佐々邸",
  "person": "専務",
  "note": "3×６　３枚　ニッショウでレンタル",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x067",
  "no": "",
  "count": 2,
  "lendDate": "2026-07-28",
  "company": "クオレホーム",
  "site": "江良邸",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x068",
  "no": "",
  "count": 8,
  "lendDate": "2026-07-30",
  "company": "パパマルハウス",
  "site": "越前邸",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x069",
  "no": "",
  "count": 0,
  "lendDate": "2026-08-08",
  "company": "玉家建設",
  "site": "小森邸",
  "person": "専務",
  "note": "3×６　２枚　ニッショウでレンタル",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x070",
  "no": "",
  "count": 3,
  "lendDate": "2026-08-22",
  "company": "東山住宅",
  "site": "山崎邸",
  "person": "北川",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x071",
  "no": "",
  "count": 5,
  "lendDate": "2026-08-27",
  "company": "クオレホーム",
  "site": "寺澤邸",
  "person": "杉村",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x072",
  "no": "",
  "count": 3,
  "lendDate": "2026-08-29",
  "company": "東山住宅",
  "site": "川上邸",
  "person": "北川",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x073",
  "no": "",
  "count": 2,
  "lendDate": "2026-09-05",
  "company": "玉家建設",
  "site": "佐川邸",
  "person": "専務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 },
 {
  "id": "x074",
  "no": "",
  "count": 1,
  "lendDate": "2026-09-05",
  "company": "玉家建設",
  "site": "稲原邸",
  "person": "専務",
  "note": "",
  "status": "active",
  "returnInfo": ""
 }
];
